name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Pacman Graph
        uses: Platane/snk@v3
        with:
          github_user_name: dhara-maru
          outputs: |
            output/pacman-contribution-graph.svg
            output/pacman-contribution-graph-dark.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add output/
          git commit -m "Generated Pacman graph" || echo "No changes to commit"
          git push
